version: '3.8'

services:

  db-service:
    image: postgres:14.0
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

networks:
  default: