version: '3.8'

services:

  db-service:
    image: postgres:14.0
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  monitoring-service:
    build: .
    ports:
      - 8081:8080
    environment:
      - APPLICATION_PORT=8080
      - DB_URL=jdbc:postgresql://db-service:5432/postgres
    depends_on:
      - db-service
    tty: true


networks:
  default:

